chore: add build script for bundling ES Module to CommonJS

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -67,3 +67,18 @@ jobs:
       with:
         file: ./coverage/lcov.info
         fail_ci_if_error: true
+  check-bundle-output:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v1
+    - run: npm install
+    - run: npm run build
+    - name: Check bundle output
+      run: |
+        if  [[ "$(git ls-files -m)" != "" ]]; then
+          echo "::error::Please build and commit these files:"
+          git ls-files -m
+          exit 1
+        fi
